# Generated by Django 5.0.4 on 2026-02-13 13:14

from django.db import migrations


def set_items_rarity_based_on_price(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    items = item_model.objects.all()

    for item in items:
        if item.price <= 10:
            item.rarity = 'Rare'
        elif 11 <= item.price <= 20:
            item.rarity = 'Very Rare'
        elif 21 <= item.price <= 30:
            item.rarity = 'Extremely Rare'
        else:
            item.rarity = 'Mega Rare'

    item_model.objects.bulk_update(items, ['rarity'])


def reverse_items_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')

    items = item_model.objects.all()

    for item in items:
        default_rarity = item_model._meta.get_field('rarity').default
        item.rarity = default_rarity
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_migrate_age_group'),
    ]

    operations = [
        migrations.RunPython(set_items_rarity_based_on_price, reverse_items_rarity)
    ]
