# Generated by Django 5.0.4 on 2026-02-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_item'),
        ('main_app', '0013_migrate_rarity_of_item'),
    ]

    operations = [
    ]
