# Generated by Django 5.0.4 on 2026-02-13 13:43

from django.db import migrations


def set_price_from_brand_length_times_120(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for smartphone in smartphones:
        new_price = len(smartphone.brand) * 120
        smartphone.price = new_price

    smartphone_model.objects.bulk_update(smartphones, ['price'])


def reverse_set_price_from_brand_length_times_120(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for smartphone in smartphones:
        default_price = smartphone._meta.get_field('price').default
        smartphone.price = default_price
        smartphone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_from_brand_length_times_120, reverse_set_price_from_brand_length_times_120)

    ]
