# Generated by Django 5.0.4 on 2026-02-13 15:05

from django.db import migrations


def set_expensive_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for smartphone in smartphones:
        if smartphone.price >= 750:
            smartphone.category = 'Expensive'
        else:
            smartphone.category = 'Cheap'

    smartphone_model.objects.bulk_update(smartphones, ['category'])


def reverse_set_expensive_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for smartphone in smartphones:
        default_category = smartphone._meta.get_field('category').default
        smartphone.category = default_category
        smartphone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_migrate_price_and_category'),
    ]

    operations = [
        migrations.RunPython(set_expensive_category, reverse_set_expensive_category)
    ]
