# Generated by Django 5.0.4 on 2026-02-13 15:18

from django.db import migrations
from django.utils import timezone


def set_delivery_and_warranty_columns(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    orders = order_model.objects.all()

    for order in orders:
        if order.status == 'Pending':
            order.delivery = order.order_date + timezone.timedelta(days=3)
            order.save()
        elif order.status == 'Completed':
            order.warranty = '24 months'
            order.save()
        else:
            order.delete()


def reverse_delivery_and_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    orders = order_model.objects.all()

    for order in orders:
        if order.status == 'Pending':
            order.delivery = None
        elif order.status == 'Completed':
            order.warranty = order_model._meta.get_field('warranty').default
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_order'),
    ]

    operations = [
        migrations.RunPython(set_delivery_and_warranty_columns, reverse_delivery_and_warranty)
    ]
