# Generated by Django 5.0.4 on 2026-03-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_stock',
            new_name='in_stock',
        ),
    ]
