# Generated by Django 5.0.4 on 2026-01-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='employee_count',
            new_name='employees_count',
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Burgas', 'Burgas'), ('Varna', 'Varna')], max_length=20),
        ),
    ]
